config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root to: "home#index"
  get 'home/index'
  devise_for :users, skip: %i[registrations sessions passwords]
  get "/users/", to: "users#index"
  get "/users/:id", to: "users#show"
  get "/users/:id/posts/", to: "posts#index"
  get "/users/:id/posts/:post_id", to: "posts#show"
  get 'users/:id/new', to: 'posts#new', as: 'new_post'
  get 'users/:id/posts/:post_id/new', to: 'comments#new', as: 'new_comment'
  get 'users/:id/posts/:post_id/new_like', to: 'likes#new', as: 'new_like'

  post 'users/:id/new', to: 'posts#create'
  post 'users/:id/posts/:post_id/new', to: 'comments#create'
  post 'users/:id/posts/:post_id/new_like', to: 'likes#create'

  #Endpoints API
  devise_scope :user do
    post 'signup', to: 'registrations#create'
    post 'login', to: 'sessions#create'
  end

  get '/api/users/:id/posts', to: "posts#index"
  get '/api/users/:id/posts/:post_id/comments', to: "posts#show"
  post '/api/users/:id/posts/:post_id/new_comment', to: "comments#create"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'
  validates :title, presence: true
  validates :text, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.recent_comments
    # A method which returns the 5 most recent comments for a given post.
    Post.order(created_at: :asc).limit(5)
  end

  def self.update_comments_counter(id)
    # A method that updates the comments counter for a post.
    @post = Post.find(id)
    @post.update(comments_counter: (@post.comments_counter + 1))
  end

  def self.update_likes_counter(id)
    # A method that updates the comments counter for a post.
    @post = Post.find(id)
    @post.update(likes_counter: (@post.likes_counter + 1))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @posts = Post.all
    @user = User.find(params[:id])

    render json: { success: true, data: { posts: @posts } }
  end

  def show
    @post = Post.find(params[:post_id])
    User.includes(:posts, :comments)

    @comments = Comment.where(post_id: params[:post_id].to_s)
    render json: { success: true, data: { posts: @comments } }
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @user = current_user
    if Post.new(post_params).invalid?
      flash[:notice] = 'The post was not saved for incorrect data'
      redirect_to "/users/#{@user.id}/"
    else
      @post = Post.create!(post_params)
      respond_to do |format|
        format.html do
          if @post.save
            # success message
            flash[:success] = 'Post saved successfully'
            # redirect to index
            redirect_to "/users/#{@post.author_id}/"
          else
            # error message
            flash.now[:error] = 'Error:  Post could not be saved'
            # render new
            render :new, locals: { post: @post }
          end
        end
      end
      User.update_post_counter(@post.author_id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text, :comments_counter, :likes_counter)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: "/users/#{params[:id]}/new/", method: :post, local: true do |f| %>
  <%= f.hidden_field :author_id, value: params[:id] %><br>
  <%= f.hidden_field :comments_counter, value: 0 %><br>
  <%= f.hidden_field :likes_counter, value: 0 %><br>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_new.html.erb
<h1 class="new-post-title">Add a new post</h1>
<%= render 'posts/form' %>

app/views/posts/index.html.erb
<h1>Here is a list of posts all posts for the user</h1>

<a href="/users/<%= @user.id %>"><div class="see-all-posts-btn"><button>Go Back</button></div></a>
<div class="users-container">
  <img class="user-photo" src=""><br>
  <h2><%= @user.name %></h2><br>
  <p class="text-usercard-index">Number of Posts: <%= @user.posts_counter %></p><br><br>
</div>
 <% @user.posts.each_with_index do |post, index| %>
<a class="link<%= post.id %>" href="/users/<%= @user.id %>/posts/<%= post.id %>">
  <div class="posts-container">
    <div class="posts-title-container">
      Post #<%= post.id %>:<br><br>
      Title: <%= post.title %><br><br>
      <%= post.text %><br>
    </div>
    <p class="post-footer-text">comments:<%= post.comments_counter %> likes:<%= post.likes_counter %></p><br><br>
  </div>
</a>
    <% post.comments.each_with_index do |comment, index| %>
    <div class="comments-container">
    <p class="comments-text"><%= User.find(comment.author_id).name %>:  <%= comment.text %> //  comment #<%= index + 1 %></p>
  </div>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1>Here is the information for Post #<%= @post.id %></h1>
<a href="/users/<%= User.find(@post.author_id).id %>/posts/"><div class="see-all-posts-btn"><button>Go Back</button></div></a>
<div class="posts-container">
  <div class="posts-title-container">
    Author: <%= User.find(@post.author_id).name %><br><br>
    Post #<%= @post.id %>:<br><br>
    Title: <%= @post.title %><br><br>
    <%= @post.text %><br>
  </div>
  <p class="post-footer-text">comments:<%= @post.comments_counter %> likes:<%= @post.likes_counter %></p><%= button_to "Like", new_like_path, params: { like: {author_id: @post.author_id, post_id: @post.id } }, method: :post %><br><br>
</div>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<div class="form-container"><%= render :partial => 'comments/new' %></div>
  <% @post.comments.each_with_index do |comment, index| %>
  <div class="comments-container">
  <p class="comments-text"><%= User.find(comment.author_id).name %>:  <%= comment.text %> //  comment #<%= index + 1 %></p>
</div>
<% end %>